import 'package:e_commerce/models/product.dart';

List<Product> products = [
  Product(
    photoUrl: "http://assets.stickpng.com/thumbs/61d4a8b48b51e20004664d4f.png",
    id: 0,
    categoryId: 1,
    name: "Rolex T-r Watch",
    isStock: true,
    price: 180,
    description: "description",
    size: "18",
    oldPrice: 200,
  ),
  Product(
    photoUrl: "http://assets.stickpng.com/thumbs/580b585b2edbce24c47b27bb.png",
    id: 1,
    categoryId: 1,
    name: "Apple Watch B2",
    isStock: true,
    price: 345,
    description: "description",
    oldPrice: 500,
    size: "size",
  ),
  Product(
    photoUrl: "http://assets.stickpng.com/thumbs/61d4a8738b51e20004664d4e.png",
    id: 2,
    categoryId: 1,
    name: "Tsrrland Vize",
    isStock: true,
    price: 3458,
    description: "description",
    oldPrice: 4000,
    size: "size",
  ),
  Product(
    photoUrl: "http://assets.stickpng.com/thumbs/580b57fbd9996e24bc43bf85.png",
    id: 3,
    categoryId: 2,
    name: "Wonder Women Bag",
    isStock: true,
    price: 200,
    description: "description",
    oldPrice: 300,
    size: "size",
  ),
  Product(
    photoUrl: "http://assets.stickpng.com/thumbs/580b57fbd9996e24bc43bf80.png",
    id: 4,
    categoryId: 2,
    name: "Human Grey Women Bag",
    isStock: true,
    price: 450,
    description: "description",
    oldPrice: 500,
    size: "size",
  ),
  // Product(
  //   photoUrl: "http://assets.stickpng.com/thumbs/580b57fbd9996e24bc43bf7f.png",
  //   id: 5,
  //   categoryId: 2,
  //   name: "Guetta Women Bag",
  //   isStock: true,
  //   price: 980,
  //   description: "description",
  //   oldPrice: 1200,
  //   size: "size",
  // ),
];
