/// Flutter icons IconsSvg
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsSvg
///      fonts:
///       - asset: fonts/IconsSvg.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsSvg {
  IconsSvg._();

  static const _kFontFam = 'IconsSvg';
  static const String? _kFontPkg = null;

  static const IconData pants_svgrepo_com = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData short_svgrepo_com = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_svgrepo_com = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoe_svgrepo_com = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tshirt_svgrepo_com = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hat_svgrepo_com = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earphones_svgrepo_com = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
